### ISSUE TITLE
run `gulp test` failed.

### ISSUE THREAD

**Issue by level5** [grommet/grommet-ferret#15]
I add a test case to test `actions.js`. configured `testPaths` in `gulpfile.js`.

when I run `gulp test`. it failed.

``` bash
$ gulp test
[01:06:24] Using gulpfile c:\git\grommet-ferret\gulpfile.js
[01:06:24] Starting 'test'...
[01:06:32] 'test' errored after 8.1 s
[01:06:32] Invariant Violation: Browser history needs a DOM
    at Object.invariant [as default] (c:\git\grommet-ferret\node_modules\invaria
nt\invariant.js:42:15)
    at createBrowserHistory (c:\git\grommet-ferret\node_modules\history\lib\crea
teBrowserHistory.js:41:100)
    at c:\git\grommet-ferret\node_modules\history\lib\useQueries.js:55:19
    at Object.<anonymous> (c:\git\grommet-ferret\src\js\RouteHistory.js:9:267)
    at Module._compile (module.js:398:26)
    at Object.moduleLoader [as .js] (c:\git\grommet-ferret\node_modules\grommet\
node_modules\gulp-jsx-coverage\index.js:159:16)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

it looks like `RouteHistory.js` need run in browser.

I added the following code to the head of `gulpfile.js` to workaround this problem. 

``` js
var jsdom = require("jsdom-no-contextify").jsdom;
global.document = jsdom('<html><body></body></html>');
global.window = document.defaultView;
global.navigator = {
  userAgent: 'node.js'
};
```

it still failed 

``` bash
$ gulp test
[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
[01:37:55] Using gulpfile c:\git\grommet-ferret\gulpfile.js
[01:37:55] Starting 'test'...
[01:38:00] 'test' errored after 5.15 s
[01:38:00] Error: Cannot find module 'index.scss'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\git\grommet-ferret\src\js\index.js:3:1)
    at Module._compile (module.js:398:26)
    at Object.moduleLoader [as .js] (c:\git\grommet-ferret\node_modules\gulp-jsx
-coverage\index.js:159:16)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

Could ferret provide a runnable test case sample? Thanks!

**Comment by alansouzati** [comment]
Fair point. Right now the test structure was only tested inside Grommet core. We added inside utils because long term we want to support a reusable testing structure for Grommet apps.

We have this in our backlog. PRs gladly appreciated.

**Comment by alansouzati** [comment]
We don't have tests for ferret as of this moment. I will work on adding tests for it soon.
