### ISSUE TITLE
npm run build failing

### ISSUE THREAD

**Issue by trsiddiqui** [grommet/grommet-ferret#47]
Just doing an npm run build after running npm run install is giving the following error.

> grommet-ferret@0.3.0 build C:\Users\aaa\Downloads\grommet-ferret-master\grommet-ferret-master
> gulp dist

[01:42:53] Requiring external module babel-register
C:\Users\aaa\Downloads\grommet-ferret-master\grommet-ferret-master\node_modules\require-dir\index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (C:\Users\aaa\Downloads\grommet-ferret-master\grommet-ferret-master\node_modules\require-dir\index.j
s:93:37)
    at Object.<anonymous> (C:\Users\aaa\Downloads\grommet-ferret-master\grommet-ferret-master\node_modules\gulp-git\in
dex.js:4:18)
    at Module._compile (module.js:641:30)
    at Module._extensions..js (module.js:652:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\aaa\Downloads\grommet-ferret-master\grommet-f
erret-master\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Users/aaa/Downloads/grommet-ferret-master/grommet-ferret-master/gulpfile.babel.js:4:1)
    at Module._compile (module.js:641:30)
    at loader (C:\Users\aaa\Downloads\grommet-ferret-master\grommet-ferret-master\node_modules\babel-register\lib\node
.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\aaa\Downloads\grommet-ferret-master\grommet-f
erret-master\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grommet-ferret@0.3.0 build: `gulp dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grommet-ferret@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aaa\AppData\Roaming\npm-cache\_logs\2017-11-23T07_42_55_364Z-debug.log

**Comment by guyvdb** [comment]
Getting the same error. Did you manage to get it built?

**Comment by redvg** [comment]
change to if (!Object.prototype.hasOwnProperty.call(require.extensions, ext)) {
