### ISSUE TITLE
Failing to build with Babel errors

### ISSUE THREAD

**Issue by nrydevopswatch** [grommet/grommet-ferret#50]
I have updated the Node (NPM) packages to the latest. First I tried to build and run as is but that failed. 

With the latest Node (NPM) packages, I'm getting the following error:
```
nrydevops@cloudshell:~/grommet-ferret (nrydevops)$ npm run build

> grommet-ferret@0.3.0 build /home/nrydevops/grommet-ferret
> gulp dist

[15:07:18] Requiring external module babel-register
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/nrydevops/grommet-ferret/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/nrydevops/grommet-ferret/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/nrydevops/grommet-ferret/gulpfile.babel.js:26:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/home/nrydevops/grommet-ferret/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/nrydevops/grommet-ferret/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at execute (/home/nrydevops/grommet-ferret/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/home/nrydevops/grommet-ferret/node_modules/gulp/node_modules/gulp-cli/index.js:201:24)
    at Liftoff.execute (/home/nrydevops/grommet-ferret/node_modules/gulp/node_modules/liftoff/index.js:201:12)
    at module.exports (/home/nrydevops/grommet-ferret/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/home/nrydevops/grommet-ferret/node_modules/gulp/node_modules/liftoff/index.js:191:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grommet-ferret@0.3.0 build: `gulp dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grommet-ferret@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nrydevops/.npm/_logs/2019-12-27T20_07_45_608Z-debug.log
nrydevops@cloudshell:~/grommet-ferret (nrydevops)$ gulp -v
CLI version: 2.2.0
Local version: 4.0.2
```

I think this is a really awesome demo of Grommet, and I would really like to update it to V2.

**Comment by nrydevopswatch** [comment]
**additional logging output**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nvm/versions/node/v10.14.2/bin/node',
1 verbose cli   '/usr/local/nvm/versions/node/v10.14.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.14.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grommet-ferret@0.3.0~prebuild: grommet-ferret@0.3.0
6 info lifecycle grommet-ferret@0.3.0~build: grommet-ferret@0.3.0
7 verbose lifecycle grommet-ferret@0.3.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle grommet-ferret@0.3.0~build: PATH: /usr/local/nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/nrydevops/grommet-ferret/node_modules/.bin:/home/nrydevops/gopath/bin:/google/gopath$
9 verbose lifecycle grommet-ferret@0.3.0~build: CWD: /home/nrydevops/grommet-ferret
10 silly lifecycle grommet-ferret@0.3.0~build: Args: [ '-c', 'gulp dist' ]
11 silly lifecycle grommet-ferret@0.3.0~build: Returned: code: 1  signal: null
12 info lifecycle grommet-ferret@0.3.0~build: Failed to exec build script
13 verbose stack Error: grommet-ferret@0.3.0 build: `gulp dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid grommet-ferret@0.3.0
15 verbose cwd /home/nrydevops/grommet-ferret
16 verbose Linux 4.19.72+
17 verbose argv "/usr/local/nvm/versions/node/v10.14.2/bin/node" "/usr/local/nvm/versions/node/v10.14.2/bin/npm" "run" "build"
18 verbose node v10.14.2
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error grommet-ferret@0.3.0 build: `gulp dist`
22 error grommet-ferret@0.3.0 build: `gulp dist`
22 error Exit status 1
23 error Failed at the grommet-ferret@0.3.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
